DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS answers;

CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  login VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE tasks (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  question VARCHAR(250) NOT NULL,
  option_1 VARCHAR(250) DEFAULT NULL,
  option_2 VARCHAR(250) DEFAULT NULL,
  option_3 VARCHAR(250) DEFAULT NULL,
  option_4 VARCHAR(250) DEFAULT NULL,
  answer VARCHAR(250) DEFAULT NULL
);

CREATE TABLE answers (
  user_id INT NOT NULL,
  task_id INT NOT NULL,
  answer VARCHAR(255) NOT NULL,
  is_passed INT(1) NOT NULL,
  CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT FK_task_id FOREIGN KEY (task_id) REFERENCES tasks(id)
);